function models = models
%MODELS - supported Ollama models

%   Copyright 2024 R. Schregle
    models = [...
        "llama3.2","llama3.2:1b",...
        "llama3.1","llama3.1:70b","llama3.1:405b",...
        "mistral-small","mistral-nemo","mistral",...
        "command-r","command-r-plus",...
    ];
end
